# Generated by Django 5.0.1 on 2024-02-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='teacher_phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
