# Generated by Django 5.0.1 on 2024-02-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_teachermodel_teacher_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='stuent_phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
