# Generated by Django 5.0.1 on 2024-02-03 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_studentmodel_stuent_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='teacher',
        ),
    ]
